# デフォルトで読み込むデータ設定ファイルを指定
defaults:
  - augmentation: image_default
  - data: interaction # 相互作用データ用の設定 'conf/data/interaction.yaml' を参照

# Hydraの実行ディレクトリ設定
hydra:
  job:
    chdir: false

# プロジェクト全体の設定
project_name: "CattleInteractionRecognition" # プロジェクト名を変更
work_dir: ${hydra:runtime.output_dir}
seed: 42

# Wandbの設定
wandb:
  project: "wacv_cattle_activity_recognition_pretrain"
  name: "interaction_${now:%Y-%m-%d_%H-%M-%S}" # 実行名を分かりやすく変更 (推奨)
  entity: null # 自身のWandbエンティティ名を設定

# モデル設定 (LitSTGCNの引数に合わせて修正)
model:
  fusion_type: attention # attention or mlp
  focal_loss_gamma: 2.0
  focal_loss_alpha: null
  embedding_size: 256    # 埋め込みベクトルの次元数
  arcface_s: 64.0        # ArcFaceのスケールファクター(通常は64)
  arcface_m: 0.5         # ArcFaceの角度マージン
  triplet_loss_weight: 0.5  # トリプレット損失の重み
  triplet_margin: 0.5  # トリプレット損失のマージン
  reg_loss_weight: 0.0  # 正則化損失の重み
  sigma_s_squared: 1.0  # 正則化損失のスケールパラメータ
  pre_fusion_loss_type: "triplet"  # ["triplet", "infonce", "none"]
  pre_fusion_loss_weight: 0.1  # 融合前の損失の重み

# 学習設定
training:
  crop_all_images: true 
  learning_rate: 1e-4
  max_epochs: 50
  accelerator: "auto"
  devices: [1]
  freeze_backbone: true
