defaults:
  - data: multi_task
  - augmentation: image_default

hydra:
  job:
    chdir: false # 出力ディレクトリをスクリプト実行場所に固定

# プロジェクト全体の設定
project_name: "CattleActionRecognition"
work_dir: ${hydra:runtime.output_dir}
seed: 42

wandb:
  project: "wacv_cattle_activity_recognition_multitask"
  name: ${now:%Y-%m-%d_%H-%M-%S}
  entity: null # ご自身のWandbエンティティ名に置き換えてください

# 本学習 (Multi-task) の設定
training:
  learning_rate: 1e-4
  max_epochs: 50
  accelerator: "gpu"
  devices: 1
  loss_weight_action: 1.0
  loss_weight_interaction: 1.0

model:
  pretrained_ckpt_path: checkpoints/interaction_split_image_metric_learning.ckpt # 事前学習済みモデルのパス